name: Github Action Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Welcome Message
        run: echo "Wecome to Github Action workflows"
      - run: ls ${{ github.workspace }}
